# Generated by Django 4.0.5 on 2022-06-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maule',
            fields=[
                ('rut', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_mat', models.CharField(max_length=200)),
                ('apellido_pat', models.CharField(max_length=200)),
                ('edad', models.IntegerField(max_length=15)),
                ('vacuna', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
