# Generated by Django 4.0.5 on 2022-06-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maule',
            name='apellido_mat',
            field=models.CharField(max_length=200, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='maule',
            name='apellido_pat',
            field=models.CharField(max_length=200, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='maule',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maule',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='maule',
            name='rut',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maule',
            name='vacuna',
            field=models.CharField(max_length=200, verbose_name='Nombre de Vacuna'),
        ),
    ]
