# Generated by Django 4.0.5 on 2022-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
